env:
  TERM: xterm-256color

window:
  padding:
    x: 3
    y: 3
  dynamic_padding: false

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Regular Italic
  size: 13

import:
  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
