import = ["/home/kalle/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = false

[window.padding]
x = 3
y = 3
